[package]
name = "poseidon"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
c_bind = ["std"]
std = []
starkware = ["sw2"]
sw2 = []
mina = []

[profile.release]
panic = "abort"
